# pyproject.toml
[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["excel_toolkit"]

[project]
name = "excel_toolkit_for_py"
version = "0.1.2"
description = "ðŸ“Š Facilite a leitura, manipulaÃ§Ã£o e exportaÃ§Ã£o de arquivos Excel e CSV com Python."
authors = [
    { name = "Roberto Lima", email = "robertolima.izphera@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.6"
license = {text = "MIT"}
dependencies = [
    "pandas>=1.0.0",
    "openpyxl>=3.0.0"
]